### PR TITLE
Fix tiles not being indexed

### LINKED ISSUE #60: Tiles aren't being indexed
Trying to run a vanilla install of meili from the new Valhalla 2.0 release and queries that previously worked with pre-2.0 meili are returning empty results.

Dug into it a bit and it looks like tiles aren't actually being indexed: an EdgeInfo's shape.size() is always 0 here:
https://github.com/valhalla/meili/blob/bbdd2fe2742c15bbd2144b6cb2e0ebde33b3f231/src/meili/candidate_search.cc#L143

/cc @kevinkreiser @kdiluca

### PR DESCRIPTION
**Pull request by ericrwolfe**
Fixes #60 (shape.size() was always returning 0)

### CODE REVIEW

File: src/meili/candidate_search.cc [hunk 1]
```diff
@@ -140,7 +140,7 @@ void IndexTile(const baldr::GraphTile& tile, baldr::GraphReader& reader, Candida
       const auto* edge = bin_tile->directededge(edge_id);
       if(edge->trans_up() || edge->trans_down() || edge->use() == baldr::Use::kTransitConnection) continue;
       //get some shape
-      const auto& shape = bin_tile->edgeinfo(edge->edgeinfo_offset()).shape();
+      const auto shape = bin_tile->edgeinfo(edge->edgeinfo_offset()).shape();
```
Comment (kevinkreiser) [inline src/meili/candidate_search.cc]: this makes a copy of the shape and shouldnt be needed. i dont see how this could possibly affect anything other than to make it slower. ill see if i can reproduce the original error.

Comment (kevinkreiser) [inline src/meili/candidate_search.cc]: im pretty sure `::shape()` returns a const reference anyway, and i do know `auto` will take on pointer or reference without you specifying that. maybe that works differently on different compilers but i would doubt the spec would allow that. what if you change this line to:

`const std::vector<PointLL>& shape = bin_tile->edgeinfo(edge->edgeinfo_offset()).shape();`

does it work then? i think we should just change this over to the lazy decoded shape anyway because thats faster since it does less allocations. i'll see if i can pr that today at some point and ill add that as another solution to the issue you raised

Comment (ericrwolfe) [inline src/meili/candidate_search.cc]: `const std::vector<PointLL>& shape` didn't work. Switching over to the lazy decoded shape sounds like much a better solution overall.

Comment (ericrwolfe) [inline src/meili/candidate_search.cc]: This actually looks unrelated to `::shape()` but rather the pointer semantics of `edgeinfo`.

Pre 2.0 the shape line looked like this:
```
const auto edgeinfo = tile.edgeinfo(offset);
const auto& shape = edgeinfo.shape();
```

Following a similar style in the current code also fixes the empty `shape.size()` problem:
```
const auto edgeinfo = bin_tile->edgeinfo(edge->edgeinfo_offset());
const auto& shape = edgeinfo.shape();
```

Comment (kevinkreiser) [inline src/meili/candidate_search.cc]: oh jeez yeah that makes perfect sense.....

when we get a reference to the shape in the one liner, we are getting a reference to an edgeinfo whose lifetime is only for that single line. after that line the edgeinfo goes out of scope and so does the reference we got from it. sorry this was very stupid on my part!

the two liner is an appropriate fix until we do the lazy shape! can you change to the two liner and we'll ship this in the mean time!

File: src/meili/candidate_search.cc [hunk 2]
```diff
@@ -140,7 +140,8 @@ void IndexTile(const baldr::GraphTile& tile, baldr::GraphReader& reader, Candida
       const auto* edge = bin_tile->directededge(edge_id);
       if(edge->trans_up() || edge->trans_down() || edge->use() == baldr::Use::kTransitConnection) continue;
       //get some shape
-      const auto& shape = bin_tile->edgeinfo(edge->edgeinfo_offset()).shape();
+      const auto edgeinfo = bin_tile->edgeinfo(edge->edgeinfo_offset());
```
Comment (kevinkreiser) [inline src/meili/candidate_search.cc]: thank you for this!
